# Preparing Data

In [2]:
import json
import pandas as pd
import numpy as np

In [14]:
# read snli

with open('data/chaosNLI/data/chaosNLI_v1.0/chaosNLI_snli.jsonl', 'r') as f:
    data = f.read()
data_dict = []
c = 0
for d in data.split('\n')[:-1]:
    data_dict.append(json.loads(d))
df_snli_full = pd.DataFrame(data_dict)

In [15]:
# read mnli

with open('data/chaosNLI/data/chaosNLI_v1.0/chaosNLI_mnli_m.jsonl', 'r') as f:
    data = f.read()
data_dict = []
c = 0
for d in data.split('\n')[:-1]:
    data_dict.append(json.loads(d))

df_mnli_full = pd.DataFrame(data_dict)

In [16]:
# combine and randomise

df_chaos_full = pd.concat([df_snli_full, df_mnli_full])
df_chaos_full = df_chaos_full.sample(frac=1, random_state=100).reset_index(drop=True)

# adding p h columns
df_chaos_full['premise'] = [x['premise'] for x in df_chaos_full['example']]
df_chaos_full['hypothesis'] = [x['hypothesis'] for x in df_chaos_full['example']]
df_chaos_full.head()

,uid,label_counter,majority_label,label_dist,label_count,entropy,example,old_label,old_labels,premise,hypothesis
0,111680e,"{'e': 91, 'n': 7, 'c': 2}",e,"[0.91, 0.07, 0.02]","[91, 7, 2]",0.505248,"{'uid': '111680e', 'premise': 'He dismounted a...",e,"[entailment, entailment, entailment, neutral, ...",He dismounted and Ca'daan saw he was smaller t...,He was shorter than the others.
1,8221794333.jpg#0r1n,"{'c': 14, 'e': 22, 'n': 64}",n,"[0.22, 0.64, 0.14]","[22, 64, 14]",1.289752,"{'uid': '8221794333.jpg#0r1n', 'premise': 'A y...",e,"[neutral, entailment, entailment, entailment, ...",A young boy in a Cookie Monster t-shirt sits o...,A young boy is playing in a pile of leaves.
2,4637931300.jpg#2r1n,"{'c': 10, 'n': 90}",n,"[0.0, 0.9, 0.1]","[0, 90, 10]",0.468996,"{'uid': '4637931300.jpg#2r1n', 'premise': 'A m...",n,"[neutral, neutral, neutral, contradiction, con...",A man in an orange construction vest walks in ...,The child has no legs.
3,36715n,"{'n': 80, 'c': 18, 'e': 2}",n,"[0.02, 0.8, 0.18]","[2, 80, 18]",0.815727,"{'uid': '36715n', 'premise': 'Jon twisted the ...",n,"[neutral, neutral, contradiction, neutral, con...",Jon twisted the man's wrist.,Jon grabbed the man and yelled at him.
4,4116163419.jpg#0r2n,"{'e': 2, 'n': 95, 'c': 3}",n,"[0.02, 0.95, 0.03]","[2, 95, 3]",0.334944,"{'uid': '4116163419.jpg#0r2n', 'premise': 'A m...",e,"[neutral, neutral, entailment, entailment, ent...",A man wearing a suit with a name tag stands re...,"A man with a name tag that reads ""Ben"" is stan..."

In [23]:
df_chaos_train = df_chaos_full[:-1000]
df_temp = df_chaos_full[-1000:]
df_chaos_val = df_temp[:-500]
df_chaos_test = df_temp[-500:]
assert len(df_chaos_train)+len(df_chaos_val)+len(df_chaos_test) == len(df_chaos_full)

In [26]:
# save to file

df_chaos_train.to_csv('data/df_chaos_train.csv', index=False)
df_chaos_val.to_csv('data/df_chaos_val.csv', index=False)
df_chaos_test.to_csv('data/df_chaos_test.csv', index=False)

In [59]:
# with open('./data/snli_1.0/snli_1.0_dev.jsonl', 'r') as f:
snli_dev = pd.read_json('./data/snli_1.0/snli_1.0_dev.jsonl', lines=True)

In [60]:
snli_dev.head()

,annotator_labels,captionID,gold_label,pairID,sentence1,sentence1_binary_parse,sentence1_parse,sentence2,sentence2_binary_parse,sentence2_parse
0,[neutral],3416050480.jpg#4,neutral,3416050480.jpg#4r1n,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,A person is training his horse for a competition.,( ( A person ) ( ( is ( ( training ( his horse...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
1,[contradiction],3416050480.jpg#4,contradiction,3416050480.jpg#4r1c,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,"A person is at a diner, ordering an omelette.",( ( A person ) ( ( ( ( is ( at ( a diner ) ) )...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
2,[entailment],3416050480.jpg#4,entailment,3416050480.jpg#4r1e,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,"A person is outdoors, on a horse.","( ( A person ) ( ( ( ( is outdoors ) , ) ( on ...",(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
3,[neutral],2267923837.jpg#2,neutral,2267923837.jpg#2r1n,Children smiling and waving at camera,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,They are smiling at their parents,( They ( are ( smiling ( at ( their parents ) ...,(ROOT (S (NP (PRP They)) (VP (VBP are) (VP (VB...
4,[entailment],2267923837.jpg#2,entailment,2267923837.jpg#2r1e,Children smiling and waving at camera,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,There are children present,( There ( ( are children ) present ) ),(ROOT (S (NP (EX There)) (VP (VBP are) (NP (NN...

In [79]:
pd.read_csv('./data/preprocessed/snli_full.csv')

,annotator_labels,gold_label,captionID,pairID,premise,hypothesis,label_count,label_dist
0,"['entailment', 'neutral', 'entailment', 'neutr...",neutral,4804607632.jpg#0,4804607632.jpg#0r1e,An older man sits with his orange juice at a s...,An elderly man sits in a small shop.,"[2, 3, 0]","[0.4, 0.6, 0.0]"
1,"['contradiction', 'contradiction', 'contradict...",contradiction,4804607632.jpg#2,4804607632.jpg#2r1c,"A few people in a restaurant setting, one of t...",The people are sitting at desks in school.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
2,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,4705552913.jpg#0,4705552913.jpg#0r1n,Two women who just had lunch hugging and sayin...,The friends have just met for the first time i...,"[0, 5, 0]","[0.0, 1.0, 0.0]"
3,"['entailment', 'entailment', 'entailment', 'en...",entailment,4705552913.jpg#3,4705552913.jpg#3r1e,"Two women, holding food carryout containers, hug.",Two women hug each other.,"[4, 0, 1]","[0.8, 0.0, 0.2]"
4,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,3636329461.jpg#0,3636329461.jpg#0r1n,The school is having a special event in order ...,A high school is hosting an event.,"[1, 4, 0]","[0.2, 0.8, 0.0]"
...,...,...,...,...,...,...,...,...
59436,"['contradiction', 'contradiction', 'contradict...",contradiction,4378810163.jpg#4,4378810163.jpg#4r1c,Two women are observing something together.,Two women are standing with their eyes closed.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
59437,"['entailment', 'entailment', 'entailment', 'co...",entailment,4378810163.jpg#4,4378810163.jpg#4r1e,Two women are observing something together.,Two girls are looking at something.,"[4, 0, 1]","[0.8, 0.0, 0.2]"
59438,"['contradiction', 'contradiction', 'contradict...",contradiction,152881593.jpg#1,152881593.jpg#1r1c,A man in a black leather jacket and a book in ...,A man is flying a kite.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
59439,"['entailment', 'entailment', 'entailment', 'ne...",entailment,152881593.jpg#1,152881593.jpg#1r1e,A man in a black leather jacket and a book in ...,A man is speaking in a classroom.,"[4, 1, 0]","[0.8, 0.2, 0.0]"
59440,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,152881593.jpg#1,152881593.jpg#1r1n,A man in a black leather jacket and a book in ...,A man is teaching science in a classroom.,"[0, 5, 0]","[0.0, 1.0, 0.0]"

In [69]:
def count_labels(labels):
    e = 0
    n = 0
    c = 0
    for l in labels:
        if l == 'entailment':
            e += 1
        elif l == 'neutral':
            n += 1
        elif l == 'contradiction':
            c += 1
        elif l == '':
            continue
        else:
            raise Exception('Label error')
    return [e, n, c]  

def label_counts_to_dist(counts):
    a = np.array(counts)
    dist = a / np.sum(a)
    return dist.tolist()

In [3]:
snli = pd.read_csv('data/preprocessed/snli_full.csv')
snli.head()

,annotator_labels,gold_label,captionID,pairID,premise,hypothesis,label_count,label_dist
0,"['entailment', 'neutral', 'entailment', 'neutr...",neutral,4804607632.jpg#0,4804607632.jpg#0r1e,An older man sits with his orange juice at a s...,An elderly man sits in a small shop.,"[2, 3, 0]","[0.4, 0.6, 0.0]"
1,"['contradiction', 'contradiction', 'contradict...",contradiction,4804607632.jpg#2,4804607632.jpg#2r1c,"A few people in a restaurant setting, one of t...",The people are sitting at desks in school.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
2,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,4705552913.jpg#0,4705552913.jpg#0r1n,Two women who just had lunch hugging and sayin...,The friends have just met for the first time i...,"[0, 5, 0]","[0.0, 1.0, 0.0]"
3,"['entailment', 'entailment', 'entailment', 'en...",entailment,4705552913.jpg#3,4705552913.jpg#3r1e,"Two women, holding food carryout containers, hug.",Two women hug each other.,"[4, 0, 1]","[0.8, 0.0, 0.2]"
4,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,3636329461.jpg#0,3636329461.jpg#0r1n,The school is having a special event in order ...,A high school is hosting an event.,"[1, 4, 0]","[0.2, 0.8, 0.0]"

In [15]:
mnli = pd.read_json('data/mnli/multinli_1.0_train.jsonl', lines=True)

In [16]:
mnli.head()

,annotator_labels,genre,gold_label,pairID,promptID,sentence1,sentence1_binary_parse,sentence1_parse,sentence2,sentence2_binary_parse,sentence2_parse
0,[neutral],government,neutral,31193n,31193,Conceptually cream skimming has two basic dime...,( ( Conceptually ( cream skimming ) ) ( ( has ...,(ROOT (S (NP (JJ Conceptually) (NN cream) (NN ...,Product and geography are what make cream skim...,( ( ( Product and ) geography ) ( ( are ( what...,(ROOT (S (NP (NN Product) (CC and) (NN geograp...
1,[entailment],telephone,entailment,101457e,101457,you know during the season and i guess at at y...,( you ( ( know ( during ( ( ( the season ) and...,(ROOT (S (NP (PRP you)) (VP (VBP know) (PP (IN...,You lose the things to the following level if ...,( You ( ( ( ( lose ( the things ) ) ( to ( the...,(ROOT (S (NP (PRP You)) (VP (VBP lose) (NP (DT...
2,[entailment],fiction,entailment,134793e,134793,One of our number will carry out your instruct...,( ( One ( of ( our number ) ) ) ( ( will ( ( (...,(ROOT (S (NP (NP (CD One)) (PP (IN of) (NP (PR...,A member of my team will execute your orders w...,( ( ( A member ) ( of ( my team ) ) ) ( ( will...,(ROOT (S (NP (NP (DT A) (NN member)) (PP (IN o...
3,[entailment],fiction,entailment,37397e,37397,How do you know? All this is their information...,( ( How ( ( ( do you ) know ) ? ) ) ( ( All th...,(ROOT (S (SBARQ (WHADVP (WRB How)) (SQ (VBP do...,This information belongs to them.,( ( This information ) ( ( belongs ( to them )...,(ROOT (S (NP (DT This) (NN information)) (VP (...
4,[neutral],telephone,neutral,50563n,50563,yeah i tell you what though if you go price so...,( yeah ( i ( ( tell you ) ( what ( ( though ( ...,(ROOT (S (VP (VB yeah) (S (NP (FW i)) (VP (VB ...,The tennis shoes have a range of prices.,( ( The ( tennis shoes ) ) ( ( have ( ( a rang...,(ROOT (S (NP (DT The) (NN tennis) (NNS shoes))...

In [6]:
cmnli = pd.read_json('data/chaosNLI/data/chaosNLI_v1.0/chaosNLI_mnli_m.jsonl', lines=True)

In [7]:
cmnli.head()

,uid,label_counter,majority_label,label_dist,label_count,entropy,example,old_label,old_labels
0,50830c,"{'c': 20, 'e': 12, 'n': 68}",n,"[0.12, 0.68, 0.2]","[12, 68, 20]",1.209800,"{'uid': '50830c', 'premise': 'um-hum um-hum ye...",n,"[contradiction, neutral, contradiction, neutra..."
1,20648n,"{'e': 48, 'n': 45, 'c': 7}",e,"[0.48, 0.45, 0.07]","[48, 45, 7]",1.295225,"{'uid': '20648n', 'premise': 'you want to punc...",n,"[neutral, neutral, contradiction, entailment, ..."
2,67610c,"{'c': 40, 'n': 12, 'e': 48}",e,"[0.48, 0.12, 0.4]","[48, 12, 40]",1.404107,"{'uid': '67610c', 'premise': 'Sorry but that's...",c,"[contradiction, contradiction, neutral, contra..."
3,47639c,"{'c': 52, 'n': 46, 'e': 2}",c,"[0.02, 0.46, 0.52]","[2, 46, 52]",1.118789,"{'uid': '47639c', 'premise': 'i'm not opposed ...",n,"[contradiction, neutral, contradiction, neutra..."
4,114458e,"{'e': 68, 'n': 29, 'c': 3}",e,"[0.68, 0.29, 0.03]","[68, 29, 3]",1.048018,"{'uid': '114458e', 'premise': 'Mortifyingly en...",e,"[entailment, neutral, entailment, neutral, ent..."

In [11]:
prepro = pd.read_csv('data/preprocessed/mnli_full.csv')
prepro1 = pd.read_csv('data/preprocessed/snli_full.csv')

In [13]:
pd.concat([prepro, prepro1], ignore_index=True)

,annotator_labels,gold_label,pairID,premise,hypothesis,label_count,label_dist,captionID
0,"['neutral', 'entailment', 'neutral', 'neutral'...",neutral,63735n,The new rights are nice enough,Everyone really likes the newest benefits,"[1, 4, 0]","[0.2, 0.8, 0.0]",NaN
1,"['contradiction', 'contradiction', 'contradict...",contradiction,91383c,This site includes a list of all award winners...,The Government Executive articles housed on th...,"[0, 0, 5]","[0.0, 0.0, 1.0]",NaN
2,"['entailment', 'entailment', 'entailment', 'en...",entailment,755e,uh i don't know i i have mixed emotions about ...,"I like him for the most part, but would still ...","[5, 0, 0]","[1.0, 0.0, 0.0]",NaN
3,"['contradiction', 'contradiction', 'contradict...",contradiction,78013c,yeah i i think my favorite restaurant is alway...,My favorite restaurants are always at least a ...,"[0, 0, 5]","[0.0, 0.0, 1.0]",NaN
4,"['contradiction', 'contradiction', 'contradict...",contradiction,96377c,i don't know um do you do a lot of camping,I know exactly.,"[0, 0, 5]","[0.0, 0.0, 1.0]",NaN
...,...,...,...,...,...,...,...,...
67837,"['contradiction', 'contradiction', 'contradict...",contradiction,4378810163.jpg#4r1c,Two women are observing something together.,Two women are standing with their eyes closed.,"[0, 0, 5]","[0.0, 0.0, 1.0]",4378810163.jpg#4
67838,"['entailment', 'entailment', 'entailment', 'co...",entailment,4378810163.jpg#4r1e,Two women are observing something together.,Two girls are looking at something.,"[4, 0, 1]","[0.8, 0.0, 0.2]",4378810163.jpg#4
67839,"['contradiction', 'contradiction', 'contradict...",contradiction,152881593.jpg#1r1c,A man in a black leather jacket and a book in ...,A man is flying a kite.,"[0, 0, 5]","[0.0, 0.0, 1.0]",152881593.jpg#1
67840,"['entailment', 'entailment', 'entailment', 'ne...",entailment,152881593.jpg#1r1e,A man in a black leather jacket and a book in ...,A man is speaking in a classroom.,"[4, 1, 0]","[0.8, 0.2, 0.0]",152881593.jpg#1
67841,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,152881593.jpg#1r1n,A man in a black leather jacket and a book in ...,A man is teaching science in a classroom.,"[0, 5, 0]","[0.0, 1.0, 0.0]",152881593.jpg#1

In [9]:
prepro.head()

,annotator_labels,gold_label,pairID,premise,hypothesis,label_count,label_dist
0,"['contradiction', 'contradiction', 'contradict...",contradiction,75290c,Your contribution helped make it possible for ...,Your contributions were of no help with our st...,"[0, 0, 5]","[0.0, 0.0, 1.0]"
1,"['contradiction', 'contradiction', 'contradict...",contradiction,133794c,"The answer has nothing to do with their cause,...",Dictionaries are indeed exercises in bi-unique...,"[0, 0, 5]","[0.0, 0.0, 1.0]"
2,"['contradiction', 'neutral', 'entailment', 'en...",entailment,3628c,We serve a classic Tuscan meal that includes ...,We serve a meal of Florentine terrine.,"[3, 1, 1]","[0.6, 0.2, 0.2]"
3,"['contradiction', 'contradiction', 'contradict...",contradiction,89411c,"A few months ago, Carl Newton and I wrote a le...",Carl Newton and I have never had any other pre...,"[0, 0, 5]","[0.0, 0.0, 1.0]"
4,"['entailment', 'entailment', 'entailment', 'en...",entailment,136158e,"I was on this earth you know, I've lived on th...",I don't yet know the reason why I have lived o...,"[5, 0, 0]","[1.0, 0.0, 0.0]"

In [22]:
temp = mnli.merge(cmnli, how='left', left_on=['pairID'], right_on=['uid'], indicator=True)

In [23]:
temp[temp['_merge'] == 'left_only']

,annotator_labels,genre,gold_label,pairID,promptID,sentence1,sentence1_binary_parse,sentence1_parse,sentence2,sentence2_binary_parse,...,uid,label_counter,majority_label,label_dist,label_count,entropy,example,old_label,old_labels,_merge
0,[neutral],government,neutral,31193n,31193,Conceptually cream skimming has two basic dime...,( ( Conceptually ( cream skimming ) ) ( ( has ...,(ROOT (S (NP (JJ Conceptually) (NN cream) (NN ...,Product and geography are what make cream skim...,( ( ( Product and ) geography ) ( ( are ( what...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,[entailment],telephone,entailment,101457e,101457,you know during the season and i guess at at y...,( you ( ( know ( during ( ( ( the season ) and...,(ROOT (S (NP (PRP you)) (VP (VBP know) (PP (IN...,You lose the things to the following level if ...,( You ( ( ( ( lose ( the things ) ) ( to ( the...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,[entailment],fiction,entailment,134793e,134793,One of our number will carry out your instruct...,( ( One ( of ( our number ) ) ) ( ( will ( ( (...,(ROOT (S (NP (NP (CD One)) (PP (IN of) (NP (PR...,A member of my team will execute your orders w...,( ( ( A member ) ( of ( my team ) ) ) ( ( will...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,[entailment],fiction,entailment,37397e,37397,How do you know? All this is their information...,( ( How ( ( ( do you ) know ) ? ) ) ( ( All th...,(ROOT (S (SBARQ (WHADVP (WRB How)) (SQ (VBP do...,This information belongs to them.,( ( This information ) ( ( belongs ( to them )...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,[neutral],telephone,neutral,50563n,50563,yeah i tell you what though if you go price so...,( yeah ( i ( ( tell you ) ( what ( ( though ( ...,(ROOT (S (VP (VB yeah) (S (NP (FW i)) (VP (VB ...,The tennis shoes have a range of prices.,( ( The ( tennis shoes ) ) ( ( have ( ( a rang...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392697,[contradiction],government,contradiction,30418c,30418,"Clearly, California can - and must - do better.","( Clearly ( , ( California ( ( ( can ( - ( and...","(ROOT (S (ADVP (RB Clearly)) (, ,) (NP (NNP Ca...",California cannot do any better.,( California ( ( ( can not ) ( do ( any better...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
392698,[neutral],travel,neutral,105454n,105454,It was once regarded as the most beautiful str...,( It ( ( ( was once ) ( regarded ( as ( ( the ...,(ROOT (S (NP (PRP It)) (VP (VBD was) (ADVP (RB...,So many of the original buildings had been rep...,( So ( ( many ( of ( the ( original buildings ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
392699,[entailment],travel,entailment,13960e,13960,Houseboats are a beautifully preserved traditi...,( Houseboats ( ( are ( ( a ( ( beautifully pre...,(ROOT (S (NP (NNS Houseboats)) (VP (VBP are) (...,The tradition of houseboats originated while t...,( ( ( The tradition ) ( of houseboats ) ) ( ( ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
392700,[neutral],slate,neutral,114061n,114061,Obituaries fondly recalled his on-air debates ...,( Obituaries ( fondly ( ( ( ( recalled ( his (...,(ROOT (S (NP (NNS Obituaries)) (ADVP (RB fondl...,The obituaries were beautiful and written in k...,( ( The obituaries ) ( ( were ( ( beautiful an...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
392701,[neutral],telephone,neutral,2065n,2065,in that other you know uh that i should do it ...,( ( ( ( in ( that other ) ) ( you ( know ( uh ...,(ROOT (SBAR (SBAR (WHPP (IN in) (WHNP (WDT tha...,My husband has been so overworked lately that ...,( ( My husband ) ( ( has ( ( been ( so overwor...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only