# Preparing Data

In [47]:
import json
import pandas as pd
import numpy as np

In [2]:
# read snli

with open('data/chaosNLI/data/chaosNLI_v1.0/chaosNLI_snli.jsonl', 'r') as f:
    data = f.read()
data_dict = []
c = 0
for d in data.split('\n')[:-1]:
    data_dict.append(json.loads(d))
df_snli_full = pd.DataFrame(data_dict)

In [3]:
# read mnli

with open('data/chaosNLI/data/chaosNLI_v1.0/chaosNLI_mnli_m.jsonl', 'r') as f:
    data = f.read()
data_dict = []
c = 0
for d in data.split('\n')[:-1]:
    data_dict.append(json.loads(d))

df_mnli_full = pd.DataFrame(data_dict)

In [14]:
# combine and randomise

df_chaos_full = pd.concat([df_snli_full, df_mnli_full])
df_chaos_full = df_chaos_full.sample(frac=1, random_state=100).reset_index(drop=True)

# adding p h columns
df_chaos_full['premise'] = [x['premise'] for x in df_chaos_full['example']]
df_chaos_full['hypothesis'] = [x['hypothesis'] for x in df_chaos_full['example']]
df_chaos_full.head()

,uid,label_counter,majority_label,label_dist,label_count,entropy,example,old_label,old_labels,premise,hypothesis
0,111680e,"{'e': 91, 'n': 7, 'c': 2}",e,"[0.91, 0.07, 0.02]","[91, 7, 2]",0.505248,"{'uid': '111680e', 'premise': 'He dismounted a...",e,"[entailment, entailment, entailment, neutral, ...",He dismounted and Ca'daan saw he was smaller t...,He was shorter than the others.
1,8221794333.jpg#0r1n,"{'c': 14, 'e': 22, 'n': 64}",n,"[0.22, 0.64, 0.14]","[22, 64, 14]",1.289752,"{'uid': '8221794333.jpg#0r1n', 'premise': 'A y...",e,"[neutral, entailment, entailment, entailment, ...",A young boy in a Cookie Monster t-shirt sits o...,A young boy is playing in a pile of leaves.
2,4637931300.jpg#2r1n,"{'c': 10, 'n': 90}",n,"[0.0, 0.9, 0.1]","[0, 90, 10]",0.468996,"{'uid': '4637931300.jpg#2r1n', 'premise': 'A m...",n,"[neutral, neutral, neutral, contradiction, con...",A man in an orange construction vest walks in ...,The child has no legs.
3,36715n,"{'n': 80, 'c': 18, 'e': 2}",n,"[0.02, 0.8, 0.18]","[2, 80, 18]",0.815727,"{'uid': '36715n', 'premise': 'Jon twisted the ...",n,"[neutral, neutral, contradiction, neutral, con...",Jon twisted the man's wrist.,Jon grabbed the man and yelled at him.
4,4116163419.jpg#0r2n,"{'e': 2, 'n': 95, 'c': 3}",n,"[0.02, 0.95, 0.03]","[2, 95, 3]",0.334944,"{'uid': '4116163419.jpg#0r2n', 'premise': 'A m...",e,"[neutral, neutral, entailment, entailment, ent...",A man wearing a suit with a name tag stands re...,"A man with a name tag that reads ""Ben"" is stan..."

In [23]:
df_chaos_train = df_chaos_full[:-1000]
df_temp = df_chaos_full[-1000:]
df_chaos_val = df_temp[:-500]
df_chaos_test = df_temp[-500:]
assert len(df_chaos_train)+len(df_chaos_val)+len(df_chaos_test) == len(df_chaos_full)

In [26]:
# save to file

df_chaos_train.to_csv('data/df_chaos_train.csv', index=False)
df_chaos_val.to_csv('data/df_chaos_val.csv', index=False)
df_chaos_test.to_csv('data/df_chaos_test.csv', index=False)

In [59]:
# with open('./data/snli_1.0/snli_1.0_dev.jsonl', 'r') as f:
snli_dev = pd.read_json('./data/snli_1.0/snli_1.0_dev.jsonl', lines=True)

In [60]:
snli_dev.head()

,annotator_labels,captionID,gold_label,pairID,sentence1,sentence1_binary_parse,sentence1_parse,sentence2,sentence2_binary_parse,sentence2_parse
0,[neutral],3416050480.jpg#4,neutral,3416050480.jpg#4r1n,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,A person is training his horse for a competition.,( ( A person ) ( ( is ( ( training ( his horse...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
1,[contradiction],3416050480.jpg#4,contradiction,3416050480.jpg#4r1c,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,"A person is at a diner, ordering an omelette.",( ( A person ) ( ( ( ( is ( at ( a diner ) ) )...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
2,[entailment],3416050480.jpg#4,entailment,3416050480.jpg#4r1e,A person on a horse jumps over a broken down a...,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,"A person is outdoors, on a horse.","( ( A person ) ( ( ( ( is outdoors ) , ) ( on ...",(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...
3,[neutral],2267923837.jpg#2,neutral,2267923837.jpg#2r1n,Children smiling and waving at camera,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,They are smiling at their parents,( They ( are ( smiling ( at ( their parents ) ...,(ROOT (S (NP (PRP They)) (VP (VBP are) (VP (VB...
4,[entailment],2267923837.jpg#2,entailment,2267923837.jpg#2r1e,Children smiling and waving at camera,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,There are children present,( There ( ( are children ) present ) ),(ROOT (S (NP (EX There)) (VP (VBP are) (NP (NN...

In [79]:
pd.read_csv('./data/preprocessed/snli_full.csv')

,annotator_labels,gold_label,captionID,pairID,premise,hypothesis,label_count,label_dist
0,"['entailment', 'neutral', 'entailment', 'neutr...",neutral,4804607632.jpg#0,4804607632.jpg#0r1e,An older man sits with his orange juice at a s...,An elderly man sits in a small shop.,"[2, 3, 0]","[0.4, 0.6, 0.0]"
1,"['contradiction', 'contradiction', 'contradict...",contradiction,4804607632.jpg#2,4804607632.jpg#2r1c,"A few people in a restaurant setting, one of t...",The people are sitting at desks in school.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
2,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,4705552913.jpg#0,4705552913.jpg#0r1n,Two women who just had lunch hugging and sayin...,The friends have just met for the first time i...,"[0, 5, 0]","[0.0, 1.0, 0.0]"
3,"['entailment', 'entailment', 'entailment', 'en...",entailment,4705552913.jpg#3,4705552913.jpg#3r1e,"Two women, holding food carryout containers, hug.",Two women hug each other.,"[4, 0, 1]","[0.8, 0.0, 0.2]"
4,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,3636329461.jpg#0,3636329461.jpg#0r1n,The school is having a special event in order ...,A high school is hosting an event.,"[1, 4, 0]","[0.2, 0.8, 0.0]"
...,...,...,...,...,...,...,...,...
59436,"['contradiction', 'contradiction', 'contradict...",contradiction,4378810163.jpg#4,4378810163.jpg#4r1c,Two women are observing something together.,Two women are standing with their eyes closed.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
59437,"['entailment', 'entailment', 'entailment', 'co...",entailment,4378810163.jpg#4,4378810163.jpg#4r1e,Two women are observing something together.,Two girls are looking at something.,"[4, 0, 1]","[0.8, 0.0, 0.2]"
59438,"['contradiction', 'contradiction', 'contradict...",contradiction,152881593.jpg#1,152881593.jpg#1r1c,A man in a black leather jacket and a book in ...,A man is flying a kite.,"[0, 0, 5]","[0.0, 0.0, 1.0]"
59439,"['entailment', 'entailment', 'entailment', 'ne...",entailment,152881593.jpg#1,152881593.jpg#1r1e,A man in a black leather jacket and a book in ...,A man is speaking in a classroom.,"[4, 1, 0]","[0.8, 0.2, 0.0]"
59440,"['neutral', 'neutral', 'neutral', 'neutral', '...",neutral,152881593.jpg#1,152881593.jpg#1r1n,A man in a black leather jacket and a book in ...,A man is teaching science in a classroom.,"[0, 5, 0]","[0.0, 1.0, 0.0]"

In [69]:
def count_labels(labels):
    e = 0
    n = 0
    c = 0
    for l in labels:
        if l == 'entailment':
            e += 1
        elif l == 'neutral':
            n += 1
        elif l == 'contradiction':
            c += 1
        elif l == '':
            continue
        else:
            raise Exception('Label error')
    return [e, n, c]  

def label_counts_to_dist(counts):
    a = np.array(counts)
    dist = a / np.sum(a)
    return dist.tolist()